In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
print(a+a)

[1 2 3 4]
[2 4 6 8]


In [2]:
b = [1,2,3,4]
print(b+b)

[1, 2, 3, 4, 1, 2, 3, 4]


In [4]:
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [6]:
a = np.array([[[1,2],[3,4]], [[1,2],[3,4]]])
print(a)

[[[1 2]
  [3 4]]

 [[1 2]
  [3 4]]]


In [7]:
a = np.array([1,2,3,4])
b = np.array([[1],[2],[3],[4]])
print(a)
print(a.shape)
print(b)
print(b.shape)

[1 2 3 4]
(4,)
[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [11]:
import numpy as np
from numpy import linalg as LA

c = np.array ([[1,2,3],[-1,1,4]])
print(LA.norm(c, axis=0))
print(LA.norm(c, axis=1))
print(LA.norm(c, ord=1, axis=1))
print(LA.norm(c, ord=2, axis=1))

[1.41421356 2.23606798 5.        ]
[3.74165739 4.24264069]
[6. 6.]
[3.74165739 4.24264069]


In [ ]:
a = np.array([[1],[2],[3],[4]])
print