In [6]:
import numpy as np

In [7]:
a = np.array([1,2,3,4])
print(a)
print(a + a)

[1 2 3 4]
[2 4 6 8]


In [8]:
b = [1, 2, 3, 4]
print(b + b)

[1, 2, 3, 4, 1, 2, 3, 4]


In [9]:
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [13]:
A = np.array([1,4,2,0], [9,5,0,0], [4, 0, 2, 4], [6, 1, 8, 3])
x = np.array([1, 2, 3, 4])
b = np.array([0, 0, 0, 0])
n = 4
for i in range(0, n):
    val = 0.0
    for j in range(0, n):
        val += A[i, j] * x[j]
    b[i] = val
print("calculate=", b)

b = np.dot(A,x)
print("dot=", b)

b = np.dot(A,x)
print("matmul=", b)

b = A@x
print("A@x=", b)

b = A*x
print("A*x=", b)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given