# 1

In [4]:
tp_ab = ('A', 'B')
tp_ab

('A', 'B')

In [7]:
tp_ab = list(tp_ab)
tp_ab.append('C')


In [8]:
tp_ab = tuple(tp_ab)
tp_ab

('A', 'B', 'C')

#2

In [26]:
n = int(input("정수 n을 입력하세요: "))

arr = [[0] * n for _ in range(n)]

num = 1
for i in range(n):
    for j in range(n):
        arr[i][j] = num
        num += 1

for i in range(n):
    for j in range(n):
        print(f"{arr[i][j]:2d}", end=" ")
    print()


정수 n을 입력하세요: 5
 1  2  3  4  5 
 6  7  8  9 10 
11 12 13 14 15 
16 17 18 19 20 
21 22 23 24 25 


In [ ]:
for i in range(n):
  for j in range(n):
    A[i, j] = n*i + j

print(A)

#3

In [27]:
import numpy as np

arr_np = np.array(arr)
reshaped_arr = arr_np.reshape(-1)

print("\n1차원으로 변환된 결과:")
print(reshaped_arr)


1차원으로 변환된 결과:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


#4

In [29]:
from PIL import Image

image_path = 'sample.jpeg'
imge = Image.open(image_path)
imge = np.array(imge)
print("원래 이미지 shape:", imge.shape)

imge_expanded = np.expand_dims(imge, axis=0)
print("expand_dims 후 shape:", imge_expanded.shape)

imge_transposed = np.transpose(imge_expanded, (0, 3, 2, 1))
print("transpose 후 shape:", imge_transposed.shape)

원래 이미지 shape: (263, 192, 3)
expand_dims 후 shape: (1, 263, 192, 3)
transpose 후 shape: (1, 3, 192, 263)


In [32]:
import cv2
frame = cv2.imread('./sample.jpeg', cv2.COLOR_BGR2RGB)
frame = frame/255

print("sample shape :",frame.shape)

frame2 = np.expand_dims(frame, 0)

frame3 = frame2.transpose(0,3,1,2)

print("sample shape :",frame3.shape)

sample shape : (263, 192, 3)
sample shape : (1, 3, 263, 192)


In [33]:
import numpy as np
from numpy import linalg as LA
c = np.array([[1, 2, 3], [-1, 1, 4]])
print(LA.norm(c, axis=0))
print(LA.norm(c, axis=1))
print(LA.norm(c, ord=1, axis=1))
print(LA.norm(c, ord=2, axis=1))


[1.41421356 2.23606798 5.        ]
[3.74165739 4.24264069]
[6. 6.]
[3.74165739 4.24264069]


In [34]:
a = np.array([1,2,3,4])
print(a)
print(a + a)

[1 2 3 4]
[2 4 6 8]


In [35]:
b = [1,2,3,4]
print(b + b)

[1, 2, 3, 4, 1, 2, 3, 4]


In [36]:
image_filename = download_file(
    "https://storage.openvinotoolkit.org/repositories/openvino_notebooks/data/data/empty_road_mapillary.jpg",
    directory="data"
)

image = cv2.imread(str(image_filename))
image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
image_h, image_w, _ = image.shape

N, C, H, W = input_layer_ir.shape

resized_image = cv2.resize(image, (W, H))

input_image = np.expand_dims(
    resized_image.transpose(2, 0, 1),
    axis=0
)
plt.imshow(rgb_image)

NameError: name 'download_file' is not defined

In [37]:
A = np.array([[1,4,2,0], [9, 5, 0, 0], [4, 0, 2, 4], [6, 1, 8, 3]])
x = np.array([1,2,3,4])
b = np.array([0,0,0,0])
n = 4
for i in range(0, n):
  val = 0.0
  for j in range(0, n):
    val += A[i,j] + x[j]
  b[i] = val

print("caculate = ", b)

b = np.dot(A,x)
print("dot=",b)

b = A @ x
print("A@x=",b)

b = A*x
print("A*x=",b)


caculate =  [17 24 20 28]
dot= [15 19 26 44]
A@x= [15 19 26 44]
A*x= [[ 1  8  6  0]
 [ 9 10  0  0]
 [ 4  0  6 16]
 [ 6  2 24 12]]


In [39]:
A = np.array([[1, 4, 2, 0], [9, 5, 0, 0], [4, 0, 2, 4], [6, 1, 8, 3]])
b = np.array([15,19,26,44])

print("det=",np.linalg.det(A))

x = np.linalg.solve(A, b)
print("solver=",x)

x = np.dot(np.linalg.inv(A),b)
print("inversel =",x)

tmp_b = np.dot(A.T,b)
tmp_T = np.dot(A.T,A)
tmp_inv = np.linalg.inv(np.dot(A.T,A))
x = np.dot(tmp_inv,tmp_b)
print("inverse2=",x)

det= 853.9999999999995
solver= [1. 2. 3. 4.]
inversel = [1. 2. 3. 4.]
inverse2= [1. 2. 3. 4.]
